Feature/django
artembelorossov/LearnDualboot pull request #3
Opened 2023-02-05 13:40 UTC by artembelorossov

Create Django project

2023-02-07 02:53 UTC, aleksandr-semenov-dbp requested changes

2023-02-07 02:53 UTC, aleksandr-semenov-dbp commented on DjangoProject/Dockerfile
> +ENV PATH="${PATH}:/root/.local/bin"
Это незачем дважды писать

2023-02-07 06:06 UTC, artembelorossov commented on DjangoProject/Dockerfile
> +ENV PATH="${PATH}:/root/.local/bin"
Исправил

2023-02-08 11:29 UTC, aleksandr-semenov-dbp approved these changes

2023-02-09 13:34 UTC, merged